import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.scss";
import Header from "../components/header";

export default function Home() {
  const [teacherActive, setTeacherActive] = useState(true);
  const [studentActive, setStudentActive] = useState(false);

  return (
    <div className={styles.Full}>
      <Header />
      <div className={styles.container}>
        <Head>
          <title>Edu Synch</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.contentContainer}>
          <section className={styles.hero}>
            <img src="detail.png" alt="Detail - Girl writing on notebook" />
          </section>

          <section className={styles.mainForm}>
            <p className={styles.formHeader}>
              Find your
              <br />
              <span>BEST TEACHER</span>
            </p>

            <p className={styles.description}>
              Whether you are a student trying to find your ideal private
              language teachers/tutors or a teacher trying to find great
              students for your customised private lessons!
            </p>

            <form>
              <input
                className={styles.searchField}
                type="text"
                name="search"
                placeholder="Type here what you are looking for"
              />
              <div className={styles.teacherStudentSelect}>
                <button
                  className={teacherActive ? styles.active : ""}
                  type="button"
                  name="teacher"
                  onClick={() => {
                    setTeacherActive(true);
                    setStudentActive(false);
                  }}
                >
                  I'M A TEACHER
                </button>
                <button
                  type="button"
                  className={studentActive ? styles.active : ""}
                  name="student"
                  onClick={() => {
                    setStudentActive(true);
                    setTeacherActive(false);
                  }}
                >
                  I'M A STUDENT
                </button>
                <button
                  onClick={(e) => {
                    e.preventDefault();
                  }}
                  className={styles.searchButton}
                >
                  SEARCH
                </button>
              </div>
            </form>
          </section>
        </main>
      </div>
    </div>
  );
}
